### ISSUE TITLE
Version 1.2.0 is not working at all

### ISSUE THREAD

**Issue by Chainbreaker1** [phasebash/jsdoc3-maven-plugin#32]
Hi,

I always get the following Exception when I try to generate the JSDoc with the version 1.2.0. With version 1.1.0 everything seems to work just fine. I get the same results in multiple projects.

```
[INFO] Generating "JsDocs" report    --- jsdoc3-maven-plugin:1.2.0
[INFO] Generating...
[INFO] js: exception from uncaught JavaScript throw: Error: Module "C:/projects/apps/ecm/myProj/target/jsdoc3/jsdoc/jsdoc.js" not found.
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:28 min
[INFO] Finished at: 2015-11-10T08:16:13+01:00
[INFO] Final Memory: 41M/683M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-site-plugin:3.3:site (default-site) on project myProj: Error during page generation: Error rendering Maven report: Unable to run all JsDoc3 Tasks. Process died with exit code 3 -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

Process finished with exit code 1
```

```
 <reporting>
        <plugins>
            <plugin>
                <groupId>com.phasebash.jsdoc</groupId>
                <artifactId>jsdoc3-maven-plugin</artifactId>
                <version>1.2.0</version>
                <configuration>
                    <sourceFiles>
                        <sourceFile>${basedir}/src/main/webapp/scripts/app.js</sourceFile>
                    </sourceFiles>
                </configuration>
            </plugin>
        </plugins>
    </reporting>
```

**Comment by phasebash** [comment]
I'll take a look this weekend if you guys can pass me your full POM configuration.  An example project would be helpful too, I understand if the original is proprietary.  

Can you help me beef up the integration test project to reproduce the issue?

**Comment by jacakk** [comment]
Same here. I think it's the problem with jsdoc3 3.3.2 (under jsdoc3-maven-plugin 1.2.0).
Try to switch jsdoc3 version.

**Comment by phasebash** [comment]
Please provide an integration test that reproduces the issue and I'll be happy to fix it.

**Comment by diogofscmariano** [comment]
I think this is happening only on windows. I'm running this Mac and no issue there while in windows the same target do not work
+1 here!

**Comment by M3lkior** [comment]
+1

**Comment by gkgeorgiev** [comment]
not working for me neither. Here's the stacktrace:

> [DEBUG] Configuring mojo com.phasebash.jsdoc:jsdoc3-maven-plugin:1.2.0:jsdoc3 from plugin realm ClassRealm[plugin>com.phasebash.jsdoc:jsdoc3-maven-plugin:1.2.0, parent: sun.misc.Launcher$AppClassLoader@74ccd249]
[DEBUG] Configuring mojo 'com.phasebash.jsdoc:jsdoc3-maven-plugin:1.2.0:jsdoc3' with basic configurator -->
[DEBUG]   (f) debug = false
[DEBUG]   (f) directoryRoots = [C:\dev\UNIONVMS\branches\dev\unionvms-web\app]
[DEBUG]   (f) includePrivate = false
[DEBUG]   (f) outputDirectory = C:\dev\UNIONVMS\branches\dev\unionvms-web\target\site\jsdoc
[DEBUG]   (f) recursive = true
[DEBUG]   (f) skip = false
[DEBUG]   (f) workingDirectory = C:\dev\UNIONVMS\branches\dev\unionvms-web\target\jsdoc3
[DEBUG] -- end configuration --
[INFO] Generating...
[INFO] js: exception from uncaught JavaScript throw: Error: Module "C:/dev/UNIONVMS/branches/dev/unionvms-web/target/jsdoc3/jsdoc/jsdoc.js" not found.
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 12.461 s
[INFO] Finished at: 2016-06-28T10:50:05+02:00
[INFO] Final Memory: 9M/244M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.phasebash.jsdoc:jsdoc3-maven-plugin:1.2.0:jsdoc3 (default-cli) on project unionvms-web: Unable to run all JsDoc3 Tasks. Process died with exit code 3 -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.phasebash.jsdoc:jsdoc3-maven-plugin:1.2.0:jsdoc3 (default-cli) on project unionvms-web: Unable to run all JsDoc3 Tasks.
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: Unable to run all JsDoc3 Tasks.
        at com.github.phasebash.jsdoc3.maven.JsDocMojo.execute(JsDocMojo.java:134)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
        ... 20 more
Caused by: com.github.phasebash.jsdoc3.maven.tasks.TaskException: Process died with exit code 3
        at com.github.phasebash.jsdoc3.maven.tasks.JsDocTask.execute(JsDocTask.java:52)
        at com.github.phasebash.jsdoc3.maven.tasks.JsDocTasks.run(JsDocTasks.java:36)
        at com.github.phasebash.jsdoc3.maven.JsDocMojo.execute(JsDocMojo.java:127)
        ... 22 more
[ERROR]

**Comment by alienfs** [comment]
I have the same issue on Windows 7 x64. I found the same issue here: https://github.com/jsdoc3/jsdoc/issues/533

It seems it was fixed on Windows in the jsdoc.cmd:
[before]
SET _BASEPATH=%_BASEPATH:\=/%

[after]
rem SET _BASEPATH=%_BASEPATH:\=/%

Can you please fix it in your plug-in?

I can send you a project if need be.

**Comment by pdefert** [comment]
the plugin doesn't work under windows 10
the problem still here
under linux it works fine
